In [2]:
import re
import os
from pathlib import Path

FOLDER = Path(os.path.dirname(os.path.realpath("__file__"))) / 'data'

### Day 01

In [3]:
in_file = 'day1.txt'

with open(FOLDER / in_file) as f:
    data = list(map(int, f))

answer1 = sum(a < b for a, b in zip(data, data[1:]))
    
trio_sums = [sum(trio) for trio in zip(data, data[1:], data[2:])]
answer2 = sum(a < b for a, b in zip(trio_sums, trio_sums[1:]))

print("solution 1:", answer1)
print("solution 2:", answer2)

solution 1: 1722
solution 2: 1748


### Day 02

In [12]:
in_file = 'day2.txt'

import numpy as np

with open(FOLDER / in_file) as f:
    data = [line.split() for line in f]

directions = {
    'forward': np.array([0, 1]),
    'down':    np.array([1, 0]),
    'up':      np.array([-1, 0])
}

# locations is an array of depth/horiz vectors
location = np.array([directions[com] * int(unit) for com, unit in data])

def solution_2_1(data):
    # depth, horiz displacement is the sum of the vectors
    return location.sum(axis=0).prod()


def solution_2_2(data):
    # depth is the horizontal displacement * cummulative sum of depth
    location[:, 0] = location[:, 1] * location[:, 0].cumsum()
    return location.sum(axis=0).prod()


print("solution 1:", solution_2_1(data))
print("solution 2:", solution_2_2(data))


solution 1: 2272262
solution 2: 2134882034


### Day 03

In [82]:
import numpy as np

in_file = 'day3.txt'

with open(FOLDER / in_file) as f:
    data = np.array([list(line.strip()) for line in f], dtype=int)

def most_common(data):
    return (data.sum(axis=0) >= data.shape[0]/2).astype(int)

def least_common(data):
    return (data.sum(axis=0) < data.shape[0]/2).astype(int)

def bin_array_to_int(arr):
    mutilplies_12bit = 1 << np.arange(11, -1, -1)
    return arr @ mutilplies_12bit

bin_array_to_int(least_common(data))

1108

In [4]:
def solution_one(data):
    gamma = bin_array_to_int(most_common(data))
    epsilon = bin_array_to_int(least_common(data))

    return gamma * epsilon

solution_one(data)

3309596

In [83]:
def solution_two(data):
    bit_length = data.shape[1]
    filtered = data

    for idx in range(bit_length):
        most = most_common(filtered)[idx]
        filtered = filtered[np.where(filtered[:,idx] == most)]
        if len(filtered) == 1:
            break

    oxygen = bin_array_to_int(filtered[0])
    
    filtered = data
    for idx in range(bit_length):
        least = least_common(filtered)[idx]
        filtered = filtered[np.where(filtered[:,idx] == least)]
        if len(filtered) == 1:
            break
    CO2 = bin_array_to_int(filtered[0])

    return oxygen * CO2
     

solution_two(data)
    

2815


2981085

### Day 4

In [362]:
in_file = 'day4.txt'

with open(FOLDER / in_file) as f:
    numbers = np.loadtxt([next(f)], delimiter=',', dtype=int)
    boards = np.loadtxt(f, dtype=int).reshape(-1, 5, 5)
    #records = f.read().split('\n\n')

#draws = [int(n) for n in records.pop(0).split(',')]
#boards = np.loadtxt(records, dtype=int).reshape(-1, 5, 5)
numbers


array([38, 54, 68, 93, 72, 12, 33,  8, 98, 88, 21, 91, 53, 61, 26, 36, 18,
       80, 73, 47,  3,  5, 55, 92, 67, 52, 25, 40, 56, 95,  9, 62, 30, 31,
       85, 65, 14,  2, 78, 75, 15, 39, 87, 27, 58, 42, 60, 32, 41, 83, 51,
       77, 10, 66, 70,  4, 37,  6, 89, 23, 16, 49, 48, 63, 94, 97, 86, 64,
       74, 82,  7,  0, 11, 71, 44, 43, 50, 69, 45, 81, 20, 28, 46, 79, 90,
       34, 35, 96, 99, 59,  1, 76, 22, 24, 17, 57, 13, 19, 84, 29])

In [315]:
a = np.zeros([5, 5])
a[1, :] = 1
a[2, 3] = 1
a[0, 0] = 1
np.apply_over_axes(np.sum, a, [0, 1])

array([[7.]])

In [228]:

np.argwhere(marks.reshape(-1, 5, 5).sum(axis=1) == 5)

array([[1, 0]])

In [199]:
marks

array([0, 1, 0, ..., 0, 0, 0])